org: rafaelram
service: api-productos

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::498917627164:role/LabRole
  environment:
    PRODUCTOS_TABLE: p_productos-${self:provider.stage}
    JWT_SECRET: mi-jwt-secret-super-seguro-y-secreto
    STAGE: ${self:provider.stage}

functions:
  crear:
    handler: src/handlers/crearProducto.lambda_handler
    events:
      - http:
          path: /productos/crear
          method: post
          cors: true
          integration: lambda
  listar:
    handler: src/handlers/listarProductos.lambda_handler
    events:
      - http:
          path: /productos/listar
          method: post
          cors: true
          integration: lambda
  buscar:
    handler: src/handlers/buscarProducto.lambda_handler
    events:
      - http:
          path: /productos/buscar
          method: post
          cors: true
          integration: lambda
  actualizar:
    handler: src/handlers/actualizarProducto.lambda_handler
    events:
      - http:
          path: /productos/actualizar
          method: post
          cors: true
          integration: lambda
  eliminar:
    handler: src/handlers/eliminarProducto.lambda_handler
    events:
      - http:
          path: /productos/eliminar
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTOS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: codigo
            AttributeType: S
          - AttributeName: categoria
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id  # PK optimizada para multi-tenant
            KeyType: HASH
          - AttributeName: codigo     # SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: CategoriaIndex
            KeySchema:
              - AttributeName: categoria
                KeyType: HASH
              - AttributeName: codigo
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES  # Requerido para CDC
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}

    ElasticsearchDomain:
      Type: AWS::Elasticsearch::Domain
      Properties:
        DomainName: productos-search-${self:provider.stage}
        ElasticsearchVersion: "7.10"
        ElasticsearchClusterConfig:
          InstanceType: "t3.small.elasticsearch"
          InstanceCount: 1
        EBSOptions:
          EBSEnabled: true
          VolumeType: "gp2"
          VolumeSize: 10
        AccessPolicies:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: {"AWS": "*"}
              Action: "es:*"
              Resource: "*"
            

    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: imagenes-productos-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred

    ProductImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ProductImagesBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::imagenes-productos-${self:provider.stage}/*"

    Outputs:
    ProductosTableName:
      Description: "Nombre tabla productos"
      Value: !Ref ProductosTable
      Export:
        Name: ${self:service}-${self:provider.stage}-ProductosTableName

    ProductosTableStreamArn:
      Description: "ARN del Stream"
      Value: !GetAtt ProductosTable.StreamArn
      Export:
        Name: ${self:service}-${self:provider.stage}-ProductosTableStreamArn

    ElasticsearchEndpoint:
      Description: "Endpoint ES"
      Value: !GetAtt ElasticsearchDomain.DomainEndpoint
      Export:
        Name: ${self:service}-${self:provider.stage}-ElasticsearchEndpoint