org: nicolasllerenas
service: productos-ingesta

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    ELASTICSEARCH_ENDPOINT: !ImportValue api-productos-${self:provider.stage}-ElasticsearchEndpoint

functions:
  actualizarProductos:
    handler: lambda_function.lambda_handler
    timeout: 30
    events:
      - stream:
          type: dynamodb
          arn: !ImportValue api-productos-${self:provider.stage}-ProductosTableStreamArn
          batchSize: 50
          startingPosition: LATEST

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true